name: CI – Vindmølle Overvågning

on:
  push:
    branches: ["main", "ttest-branch"]
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Byg Docker image
        run: docker build -t vindmolle-app .